module.exports={
    entry:'./src/index.js',
    output:{
        path:path.join(__dirname,"dist"),
        filename:'[name].[hash].js'
    },
    module:{
        rules:{
            test:/\.css$/,
            use:[]
        }
    },
    plugin:{},
    devServer:{
        contentBase:path.join(__dirname,"dist"),
        port:9090,
        host:'localhost',
        overlay:true,
        compress:true
    }
}